name: Build and Deploy .NET App with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Build Stage #
  ci-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # Unit Test Stage
  unit-test:
    runs-on: ubuntu-latest
    needs: ci-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

  lacework-scan:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan the repo for vulnerabilities in IaC
        run: |
             # Required to pass the GITHUB and Lacework (LW) environment variables to use
             env | grep "GITHUB_\|LW_\|CI_" > env.list
             # Required command based on what you want to scan in the repository
             echo "SCAN_COMMAND=tf-scan" >> env.list
             # Required if you are not mounting the volume on /app
             echo "WORKSPACE=src" >> env.list
             # if we want to fail the step for any critical failed findings (violations) in the assessment scan
             #echo "EXIT_FLAG='critical'" >> env.list 
             docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}

  #lacework-app-scan:
  #  runs-on: ubuntu-latest
  #  needs: lacework-scan
  #
  #  steps: 
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #
  #    - name: First message
  #      run: echo "This will be the application validation stage"


  # CD Deploy Stage ##
  cd-deploy:
    runs-on: ubuntu-latest
    needs: lacework-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Credentials as Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init \
            -backend-config="storage_account_name=tspontes7xg2dfzesta001" \
            -backend-config="container_name=terraform" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="sas_token=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiyx&se=2024-06-26T20:08:08Z&st=2024-06-26T12:08:08Z&spr=https,http&sig=DRxJpnzKAKp7snOS2rg5xdEa%2B3ieID1QqHzhXaDvbdU%3D"

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Debug Terraform Outputs
        run: |
          cd terraform
          terraform output -json

      - name: Output Azure App Service Name
        id: output
        working-directory: terraform
        run: |
          app_service_name=$(terraform output -raw app_service_name)
          resource_group_name=$(terraform output -raw resource_group_name)
          echo "App Service Name: $app_service_name"
          echo "Resource Group Name: $resource_group_name"
          echo "app_service_name=$app_service_name" >> $GITHUB_ENV
          echo "resource_group_name=$resource_group_name" >> $GITHUB_ENV

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Retrieve Azure App Service Publish Profile
        id: retrieve-profile
        run: |
          az webapp deployment list-publishing-profiles --resource-group ${{ env.resource_group_name }} --name ${{ env.app_service_name }} --output json > publishProfile.json
          cat publishProfile.json
  
      - name: Set Publish Profile as Secret
        id: set-profile
        run: |
          echo "AZUREAPPSERVICE_PUBLISHPROFILE=$(cat publishProfile.json | jq -c .)" >> $GITHUB_ENV
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app_service_name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'Production'
          package: .
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        
